name: build

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write
  packages: write
  security-events: write

jobs:
  image:
    uses: vexxhost/github-actions/.github/workflows/image.yml@main
    with:
      image-ref: ghcr.io/${{ github.repository_owner }}/ubuntu
      push: ${{ github.event_name == 'push' }}
