name: periodic

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - uses: vexxhost/github-actions/scan-image@main
        with:
          image-ref: ghcr.io/${{ github.repository_owner }}/ubuntu
