name: publish

on:
  push:
    branches:
      - main

jobs:
  image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ghcr.io/${{ github.repository_owner }}/ubuntu
          tags: |
            type=sha
            type=edge
            type=edge,suffix=-{{date 'X'}}
      - uses: depot/setup-action@v1
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: depot/build-push-action@v1
        id: build
        with:
          context: .
          project: h8rjlfhzg5
          platforms: linux/amd64,linux/arm64
          push: true
          sbom: true
          provenance: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - uses: winterjung/split@v2
        id: split
        with:
          msg: ${{ fromJSON(steps.build.outputs.metadata)['image.name'] }}
          separator: ","
      - uses: aquasecurity/trivy-action@0.30.0
        with:
          image-ref: ${{ steps.split.outputs._0 }}
          ignore-unfixed: true
          format: sarif
          output: trivy-results.sarif
      - uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: trivy-results.sarif
    outputs:
      image_name: ${{ steps.split.outputs._0 }}

  sbom:
    runs-on: ubuntu-latest
    needs: image
    permissions:
      contents: write
      security-events: write
    steps:
      - name: Scan image in a private registry
        uses: aquasecurity/trivy-action@0.30.0
        with:
          image-ref: ${{ needs.image.outputs.image_name }}
          format: github
          output: dependency-results.sbom.json
          github-pat: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v4
        with:
          name: trivy-sbom-report
          path: "${{ github.workspace }}/dependency-results.sbom.json"
